export enum assetPaths {
  HOME_BACKGROUND = "assets/home_background.png",
  LOGO_WITH_TEXT = "assets/logo_with_text.png",
  LOGO = "assets/logo.png",
  POLYGONS = "assets/polygons.png",
  POLYGONS_BACKGROUND = "assets/polygons_background.png",
  POLYGONS_BACKGROUND_2 = "assets/polygons_background_2.png",
  QUARRYCHAIN_NAME = "assets/quarrychain_name.png",
  CHART = "assets/chart.png",
  TURQUOISE_BACKGROUND = "assets/turquoise_background.png",
  QUARRY_WALLET = "assets/quarry_wallet.png",
  BLOCK_EXPLORER = "assets/block_explorer.png",
  QUARRY_COIN_HEXAGON = "assets/quarry_coin_hexagon.png",
  QUARRY_COIN = "assets/quarry_coin.png",
  TUFF_TOKEN_HEXAGON = "assets/tuff_token_hexagon.png",
  TUFF_TOKEN = "assets/tuff_token.png",
  MOAI_TOKEN_HEXAGON = "assets/moai_token_hexagon.png",
  MOAI_TOKEN = "assets/moai_token.png",
  TAP_TOKEN_HEXAGON = "assets/tap_token_hexagon.png",
  TAP_TOKEN = "assets/tap_token.png",
  HIGH_THROUGHTPUT = "assets/high_throughput.png",
  HIGH_AVAILABILITY = "assets/high_availability.png",
  HIGH_SCALABILITY = "assets/high_scalability.png",
}
